version: '3'

services:
  web:
    image: nginx
    container_name: umi-app
    ports:
      - "8000:8000"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf